import React from "react";
import Head from "next/head";
import { BsFillMoonStarsFill, BsFillSunFill, BsTypeH3 } from "react-icons/bs";
import Image from "next/image";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai";
import studying from "../public/studying.png";



const Intro = function ({toggleMoon, toggleSun, darkMode, toggleDarkMode}) {
  return (
    <>
      <Head>
        <title>Omri Ronen&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/robot.ico" />
      </Head>

      <section className="min-h-fit">
        <nav className="py-10 mb-12 flex justify-between dark:text-white">
          <h1 className="font-burtons text-xl">Welcome!</h1>

          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill
                style={{ display: "none" }}
                onClick={() => {
                  toggleSun();
                  toggleDarkMode();
                }}
                className=" cursor-pointer text-2xl"
                id="moon"
              />
              <BsFillSunFill
                onClick={() => {
                  toggleMoon();
                  toggleDarkMode();
                }}
                className="cursor-pointer text-2xl"
                id="sun"
              />
            </li>
            <li>
              <a
                href="https://omri-ronen.vercel.app/resume.pdf"
                download
                className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                rel="noopener noreferrer"
                target="_blank"
              >
                Resume
              </a>
            </li>
          </ul>
        </nav>
        <div className="text-center p-10 py-10">
          <h2 className="cursive-font text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
            Omri Ronen
          </h2>

          <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
            Developer and designer.
          </h3>
          <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Front-end developer leveraging a multidisciplniary background.
            Excited about developing new projects and working with fun &
            creative people.
          </p>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a
              rel="noreferrer"
              target="_blank"
              href="https://twitter.com/OmriRonen1"
              className="hover:transform duration-500 hover:scale-105"
            >
              <AiFillTwitterCircle />
            </a>
            <a
              rel="noreferrer"
              target="_blank"
              href="https://www.linkedin.com/in/omri4/"
              className="hover:transform duration-500 hover:scale-105"
            >
              <AiFillLinkedin />
            </a>
            <a
              rel="noreferrer"
              target="_blank"
              href="https://github.com/Omrironen4"
              className="hover:transform duration-500 hover:scale-105"
            >
              <AiFillGithub />
            </a>
          </div>
          <div className="mt-10">
            <Image
              priority
              className="image"
              height={450}
              width={450}
              alt="project"
              src={studying}
            />
          </div>
        </div>
      </section>
    </>
  );
};

export default Intro;
